#!/bin/sh -e

CC=cc CXX=c++ \
./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --with-logdir=/var/log/cups \
    --with-cups-user=lp \
    --with-cups-group=lp \
    --with-languages=en \
    --without-pam \
    --without-rcdir \
    --with-optim="$CFLAGS" \
    --disable-webif \
    --disable-gnutls \
    --disable-gssapi \
    --disable-systemd

make
make BUILDROOT="$1" install

# conflict with cups-filters
rm -r "$1/usr/share/cups/banners" \
    "$1/usr/share/cups/data"

# cleanup
rm -rf "$1/usr/share/applications" \
    "$1/usr/share/icons" \
    "$1/usr/share/cups/templates"
chmod 0755 "$1/var/cache" \
    "$1/var/spool"
chmod -R +w "$1"

# start script
#install -D -m 755 cups.rc "$1/etc/rc.d/cups"
